import type { Product } from "../registry/default/types/product";

export const products: ReadonlyArray<Product> = [
  {
    id: "alo-yoga/airbrush-legging",
    vendor: "Alo Yoga",
    name: "High-Waist Airbrush Legging",
    subtitle: "8 colors · XXS to XL",
    image: { url: "https://picsum.photos/seed/airbrush-legging/600/750" },
    price: { currency: "USD", value: "118.00" },
    pointsPrice: 11800,
    availability: { kind: "in-stock" },
    marketplace: "shopify",
  },
  {
    id: "norse/sigfred-merino",
    vendor: "Norse Projects",
    name: "Sigfred Merino Crew Sweater",
    subtitle: "5 colors · XS to XL",
    image: { url: "https://picsum.photos/seed/sigfred-merino/600/750" },
    price: { currency: "USD", value: "245.00" },
    pointsPrice: 24500,
    availability: { kind: "in-stock" },
    marketplace: "shopify",
  },
  {
    id: "acne/cashmere-beanie",
    vendor: "Acne Studios",
    name: "Cashmere Ribbed Beanie",
    subtitle: "Black",
    image: { url: "https://picsum.photos/seed/acne-beanie/600/750" },
    price: { currency: "USD", value: "185.00" },
    availability: { kind: "out-of-stock" },
    marketplace: "shopify",
  },
  {
    id: "bose/quietcomfort",
    vendor: "Bose",
    name: "QuietComfort Ultra Earbuds",
    subtitle: "Black",
    image: { url: "https://picsum.photos/seed/bose-qc/600/750" },
    price: { currency: "USD", value: "299.00" },
    availability: { kind: "marketplace-down", marketplace: "amazon" },
    marketplace: "amazon",
  },
  {
    id: "bellroy/apex",
    vendor: "Bellroy",
    name: "Apex Slim Sleeve, Cognac",
    subtitle: "Top-grain leather",
    image: { url: "https://example.invalid/this-does-not-exist.jpg" },
    price: { currency: "USD", value: "135.00" },
    pointsPrice: 13500,
    availability: { kind: "in-stock" },
    marketplace: "shopify",
  },
];
